# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict
from typing import List

from pydantic import BaseModel
from pydantic import Extra


class FfMainStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    campaign_list: Dict[str, str]
    crowdfunding_categories: List[str]
    version: str
