# generated by datamodel-codegen:
#   filename:  close_campaign.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class CloseCampaignParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
