# generated by datamodel-codegen:
#   filename:  send_funds.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class SendFundsParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
